UCRMS/Controllers/CourseController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UCRMS.BLL;
using UCRMS.Models.EntityModels;

namespace UCRMS.Controllers
{
    public class CourseController : Controller
    {
        CourseManager _courseManager = new CourseManager();
        SemesterManager _semesterManager = new SemesterManager();
        DepartmentManager _departmentManager = new DepartmentManager();

        // GET: Course
        [HttpGet]
        public ActionResult Save()
        {
            var departments = _departmentManager.GetAll() ?? new List<Department>();
            var semesters = _semesterManager.GetAll() ?? new List<Semester>();
            ViewBag.Semesters = new SelectList(semesters, "Id", "Name");
            ViewBag.Departments = new SelectList(departments, "Id", "Name");
            return View();
        }

        // POST: Course
        [HttpPost]
        public ActionResult Save(Course course)
        {
            var departments = _departmentManager.GetAll() ?? new List<Department>();
            var semesters = _semesterManager.GetAll() ?? new List<Semester>();
            ViewBag.Semesters = new SelectList(semesters, "Id", "Name");
            ViewBag.Departments = new SelectList(departments, "Id", "Name");

            if (ModelState.IsValid)
            {
                ArrayList status = _courseManager.Save(course);
                ViewBag.Status = status;
                if ((bool) status[0])
                {
                    ModelState.Clear();
                    return View();
                }
                return View(course);
            }
            return View(course);
        }

        [HttpGet]
        public ActionResult ViewCourseStatics()
        {
            var departments = _departmentManager.GetAll() ?? new List<Department>();
            ViewBag.Departments = new SelectList(departments,"Id","Name");
            return View();
        }

        public JsonResult GetCourseStaticsByDepartmentId(int departmentId)
        {
            var courses = _courseManager.GetCourseStaticsByDepartmentId(departmentId);
            return Json(courses, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult UnassignAllCourses()
        {
            return View();
        }

        [HttpPost]
        public ActionResult UnassignAllCourses(bool isClicked)
        {
            if (isClicked)
            {
                ViewBag.Status = _courseManager.UnassignAllCourses();
            }
            return View();
        }
    }
}

UCRMS/Controllers/DepartmentController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UCRMS.BLL;
using UCRMS.Models.EntityModels;

namespace UCRMS.Controllers
{
    public class DepartmentController : Controller
    {
        DepartmentManager _departmentManager = new DepartmentManager();
        
        // GET: Department
        [HttpGet]
        public ActionResult Save()
        {
            return View();
        }

        // POST: Department
        [HttpPost]
        public ActionResult Save(Department department)
        {
            if (ModelState.IsValid)
            {
                ArrayList status = _departmentManager.Save(department);
                ViewBag.Status = status;
                if ((bool) status[0])
                {
                    ModelState.Clear();
                    return View(new Department());
                }
                return View(department);
            }
            return View(department);
        }

        // GET: Show All Departments
        [HttpGet]
        public ActionResult ViewAll()
        {
            var departments = _departmentManager.GetAll();
            if (departments != null)
            {
                return View(departments);
            }
            ViewBag.Message = "No records found.";
            return View(new List<Department>());
        }
    }
}

UCRMS/Controllers/RoomController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UCRMS.BLL;
using UCRMS.Models.EntityModels;
using UCRMS.Models.ViewModels;

namespace UCRMS.Controllers
{
    public class RoomController : Controller
    {
        ClassRoomManager _classRoomManager = new ClassRoomManager();
        DepartmentManager _departmentManager = new DepartmentManager();
        CourseManager _courseManager = new CourseManager();

        private readonly List<Day> _days = new List<Day>
        {
            new Day{Id = 1,Code = "Sat",Name = "Saturday"},
            new Day{Id = 2,Code = "Sun",Name = "Sunday"},
            new Day{Id = 3,Code = "Mon",Name = "Monday"},
            new Day{Id = 4,Code = "Tue",Name = "Tuesday"},
            new Day{Id = 5,Code = "Wed",Name = "Wednesday"},
            new Day{Id = 6,Code = "Thu",Name = "Thursday"},
            new Day{Id = 7,Code = "Fri",Name = "Friday"},
        };

        // GET: Room
        [HttpGet]
        public ActionResult AllocateClass()
        {
            var rooms = _classRoomManager.GetAllRooms() ?? new List<Room>();
            var departments = _departmentManager.GetAll() ?? new List<Department>();
            ViewBag.Departments = new SelectList(departments, "Id", "Name");
            ViewBag.Rooms = new SelectList(rooms, "Id", "Name");
            ViewBag.Days = new SelectList(_days,"Code","Name");
            return View();
        }

        [HttpPost]
        public ActionResult AllocateClass(ClassRoomCourse classRoomCourse)
        {
            var rooms = _classRoomManager.GetAllRooms() ?? new List<Room>();
            var departments = _departmentManager.GetAll() ?? new List<Department>();
            ViewBag.Departments = new SelectList(departments, "Id", "Name");
            ViewBag.Rooms = new SelectList(rooms, "Id", "Name");
            ViewBag.Days = new SelectList(_days, "Code", "Name");

            if (ModelState.IsValid)
            {
                ArrayList status = _classRoomManager.AllocateClass(classRoomCourse);
                ViewBag.Status = status;
                if ((bool) status[0])
                {
                    ModelState.Clear();
                    return View();
                }
                return View(classRoomCourse);
            }
            return View(classRoomCourse);
        }

        public JsonResult GetAllCourseByDepartmentId(int departmentId)
        {
            var courses = _courseManager.GetAllCourseByDepartmentId(departmentId);
            return Json(courses, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ShowClassSchedule()
        {
            var departments = _departmentManager.GetAll() ?? new List<Department>();
            ViewBag.Departments = new SelectList(departments, "Id", "Name");
            return View();
        }

        public JsonResult GetClassRoomAllocationInfoByDepartmentId(int departmentId)
        {
            var classSchedules = _classRoomManager.GetClassRoomAllocationInfoByDepartmentId(departmentId);
            return Json(classSchedules, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult UnAllocateClassRoom()
        {
            return View();
        }

        [HttpPost]
        public ActionResult UnAllocateClassRoom(bool isClicked)
        {
            if (isClicked)
            {
                ViewBag.Status = _classRoomManager.UnAllocateClassRoom();
            }
            return View();
        }
    }
}

UCRMS/Controllers/TeacherController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UCRMS.BLL;
using UCRMS.Models.EntityModels;
using UCRMS.Models.ViewModels;

namespace UCRMS.Controllers
{
    public class TeacherController : Controller
    {
        DesignationManager _designationManager = new DesignationManager();
        DepartmentManager _departmentManager = new DepartmentManager();
        TeacherManager _teacherManager = new TeacherManager();
        CourseManager _courseManager = new CourseManager();

        // GET: Teacher
        [HttpGet]
        public ActionResult Save()
        {
            var designations = _designationManager.GetAll() ?? new List<Designation>();
            var departments = _departmentManager.GetAll() ?? new List<Department>();
            ViewBag.Designations = new SelectList(designations, "Id", "Name");
            ViewBag.Departments = new SelectList(departments, "Id", "Name");
            return View();
        }

        [HttpPost]
        public ActionResult Save(Teacher teacher)
        {
            var designations = _designationManager.GetAll() ?? new List<Designation>();
            var departments = _departmentManager.GetAll() ?? new List<Department>();
            ViewBag.Designations = new SelectList(designations, "Id", "Name");
            ViewBag.Departments = new SelectList(departments, "Id", "Name");

            if (ModelState.IsValid)
            {
                ArrayList status = _teacherManager.Save(teacher);
                ViewBag.Status = status;
                if ((bool) status[0])
                {
                    ModelState.Clear();
                    return View(); 
                }
                return View(teacher);
            }

            return View(teacher);
        }

        [HttpGet]
        public ActionResult AssignCourse()
        {
            var departments = _departmentManager.GetAll() ?? new List<Department>();
            ViewBag.Departments = new SelectList(departments, "Id", "Name");
            return View();
        }


        [HttpPost]
        public ActionResult AssignCourse(TeacherCourse teacherCourse)
        {
            var departments = _departmentManager.GetAll() ?? new List<Department>();
            ViewBag.Departments = new SelectList(departments, "Id", "Name");

            if (ModelState.IsValid)
            {
                ArrayList status = _teacherManager.AssignCourse(teacherCourse);
                ViewBag.Status = status;
                if ((bool) status[0])
                {
                    ModelState.Clear();
                    return View();
                }
                return View(teacherCourse);
            }
            return View(teacherCourse);
        }

        public JsonResult GetAllTeacherAndCourseByDepartmentId(int departmentId)
        {
            var teachers = _teacherManager.GetAllTeacherByDepartmentId(departmentId);
            var courses = _courseManager.GetAllCourseByDepartmentId(departmentId);
            var teachersAndCourses = new
            {
                Teachers = teachers,
                Courses = courses
            };
            return Json(teachersAndCourses, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetTeacherCourseCreditInfoByTeacherId(int teacherId)
        {
            var teacher = _teacherManager.GetTeacherCourseCreditInfoByTeacherId(teacherId);
            return Json(teacher, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetCourseInfoByCourseId(int courseId)
        {
            var course = _courseManager.GetCourseInfoByCourseId(courseId);
            return Json(course, JsonRequestBehavior.AllowGet);
        }
    }
}

UCRMS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - UCRMS</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("styles",required:false)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("UCRMS", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Department <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Save", "Save", "Department")</li>
                            <li>@Html.ActionLink("View All", "ViewAll", "Department")</li>
                        </ul>
                    </li>
                    <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Course <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Save", "Save", "Course")</li>
                            <li>@Html.ActionLink("View Course Statics", "ViewCourseStatics", "Course")</li>
                            <li>@Html.ActionLink("Unassign All Courses", "UnassignAllCourses", "Course")</li>
                        </ul>
                    </li>
                    <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Teacher <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Save", "Save", "Teacher")</li>
                            <li>@Html.ActionLink("Assign Course", "AssignCourse", "Teacher")</li>
                        </ul>
                    </li>
                    <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Student <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Register Student", "Register", "Student")</li>
                            <li>@Html.ActionLink("Enroll in a Course", "EnrollCourse", "Student")</li>
                            <li>@Html.ActionLink("Save Student Result", "SaveResult", "Student")</li>
                            <li>@Html.ActionLink("View Result", "ShowResult", "Student")</li>
                        </ul>
                    </li>
                    <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Class Room <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Allocate Class Room", "AllocateClass", "Room")</li>
                            <li>@Html.ActionLink("Show Class Schedule", "ShowClassSchedule", "Room")</li>
                            <li>@Html.ActionLink("Unallocate Classrooms", "UnAllocateClassRoom", "Room")</li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>
    <footer>
        <p>&copy; All Copyrights @DateTime.Now.Year Reserved - UCRMS | BITM [Arif]</p>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryval")

    @RenderSection("scripts", required: false)
</body>
</html>